apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-authenticator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: basicauthenticator
    app.kubernetes.io/part-of: basicauthenticator
  {{- include "simple-authenticator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}